### ISSUE TITLE
Soldering 5V port on PCB

### ISSUE THREAD

**Issue by Hackerman2016** [openMLA/elegoo-mars-4-dlp-controller#4]
So I have built the PCB according to the instructions, and I was wondering whether or not to solder the 5V port on the PCB, and after the PCB is complete, what is ideally the next step? I have to install the packages as specified on the pi and run the main.py, and it should work?

**Comment by NemoAndrea** [comment]
The 5V pin on the PCB (assuming we are talking about the same pin), can be left out; it is just there in case you want to power something with the 5V from the pi/dcdc converter. 

If you are taking about the solder bridge: it should be soldered if you have a the  dc-dc converter (CUI P78E)  soldered in place; if you don't have the CUI, then it doesn't really matter if you close the solder bridge. 

> [!WARNING]
> Whatever you do, do not power the raspberry pi through USB and the CUI converter at the same time. It is **either** power through the USB connector of the pi (leave the 5V solder bridge empty, and leave out the CUI) **or** power through the 12V barrel jack with the CUI to provide the 5V power for the Pi.

If you have assembled the board and checked that the pi still works (I suggest you do this before connecting the projector). then you hook up the projector, follow the software packages instructions and then indeed try main.py.

If that all works you can start writing your own python code for your project  using the included code :)

**Comment by Hackerman2016** [comment]
I have the dc-dc converter in place.
![IMG_1457](https://github.com/openMLA/elegoo-mars-4-dlp-controller/assets/170014411/3b83b9d4-290c-4833-bf8a-678bc29186a3)
This is the 5V port I am talking about.

**Comment by NemoAndrea** [comment]
Ah yes, that one you should bridge if you have the dc-dc converter installed. This connects the 12V to the input of the converter. It is there to allow you to quickly 'disconnect' the dc-dc converter if you ever want to connect/power the pi over USB. (easier to remove the solder bridge than to desolder the dc-dc converter)

To reiterate (to prevent damage), do not connect USB power to the pi if you also connect the 12V at the same time.

**Comment by Hackerman2016** [comment]
Ah, okay. Great. Thanks a lot.
