### ISSUE TITLE
Regarding running the python code

### ISSUE THREAD

**Issue by Hackerman2016** [openMLA/elegoo-mars-4-dlp-controller#5]
![Error](https://github.com/openMLA/elegoo-mars-4-dlp-controller/assets/170014411/eeae89f1-f27f-464b-b47f-6d81d71d40e1)

I have connected all the components and have managed to power on the printer after connecting the pcb and pi but as soon as I run the code I get this error. Any help with this will be appreciated. Also I have trouble in connecting the pi to the internet. Doing configuring the rasbian os 64 bit on the pi zero 2W I did the ssh settings but still somehow when I login on putty with the hostname I get an error saying hostname doesn't exist.

**Comment by Hackerman2016** [comment]
Also when I am trying to increase the SPI buffer size I followed the steps mentioned in the document but I am unable to do it. I am getting this error.
![Directory doesn't exist](https://github.com/openMLA/elegoo-mars-4-dlp-controller/assets/170014411/33b06977-ebbb-4d38-8726-f0e9781f8dda)

**Comment by NemoAndrea** [comment]
Hmm for the first point, could it be that you are running the python code on your local machine and not on the raspberry pi? If not then you need to install RPi.GPIO but I think that should definitely come with the default OS.

For the 2nd image, why is there `firmware` in the path?  It should just be `/boot/cmdline.txt`; that might fix it

**Comment by Hackerman2016** [comment]
For the first point you were right I was trying to run it on local machine. Running it on Pi solved the issue and yeah about making changes in the /boot/cmdline.txt file, for me after running that command I get an error saying that the file has been shifted to /boot/firmware/cmdline.txt. That's why increasing the buffer size and stuff I have all done it in that file.

**Comment by NemoAndrea** [comment]
Hmm, strange, I am not aware of this change. I guess there must be a file `cmdline.txt` somewhere on the system. Maybe you can post raspberry pi os version here, so that other people can figure out if they may be running a version with issues too.

**Comment by Hackerman2016** [comment]
That is a difference I am not working with the OS lite and Pi Zero. I am working with the Raspberry Pi 3b+ and the standard Raspberry OS 64-bit.

**Comment by NemoAndrea** [comment]
Is this issue still giving problems, or is it all behaving now that I2C is working?

**Comment by Hackerman2016** [comment]
It's all working, now that I2C has started working. Now I am just trying to project different images but I'm getting errors while doing that so just figuring that out.

**Comment by NemoAndrea** [comment]
Okay, I will close this issue, as I think it would be better to make a more focussed new issue if you cannot figure it out. Nice to see you being able to get the project working (at least in parts!). 

If you run into issues where the documentation is wrong or even just unclear, let me know because that is super valuable for the project :)
