### ISSUE TITLE
Projector not quite working

### ISSUE THREAD

**Issue by davidsachs** [openMLA/elegoo-mars-4-dlp-controller#8]
I hooked everything up and followed the software setup instruction, the projector is projecting, but not projecting the patterns I expect, and a few things are not working. For example, if I run:

DMD.set_background(intensity=15, both_buffers = False)

I would expect the entire image to be darker, but it isn't. However, if I run the above line multiple times, then part of the image is darker, depending on how many times I run it. So this suggests to me that something is weird with the SPI protocol and the splitting up of the data, or maybe of the end of the SPI command for each chunk. 

The image is also flickering, so it's possible there's a solder issue somewhere. But oddly if I run main.py, it projects a bunch of times (but just sort of turning on and off, not projecting images), and reliably flickers at the beginning of the program but not at the end. So could the flickering somehow be due to the software?

I'm also getting the "PRINT ACTIVE did not go high after starting exposure" error message.

Raspberry pi is 358-SC1146 from Mouser, running 32 bit Bullseye

**Comment by NemoAndrea** [comment]
Not that I think it would matter much, but are your running Raspberry OS lite, or with desktop?

I think the `PRINT ACTIVE` message can be ignored.

Some images may be useful for debugging. Here is a video of it working on my zero

Some flickering is expected i.i.r.c. as the unit targets a 30Hz or so refresh rate. I think there should be ways to avoid that, but for now that hasn't been something I have worked on.

https://github.com/user-attachments/assets/020fbf53-90c2-4a46-b2de-2d167c933b9b

**Comment by davidsachs** [comment]
It's the lite OS, not desktop.

I checked the connections with a multimeter and touched up the soldering, the behavior is the same. Maybe it's an SPI protocol issue?
Here's a video of main.py (the light is saturating my cell phone camera, so it looks a little weird)

https://github.com/user-attachments/assets/2da4987a-22ab-4abb-8392-633d9e833592

I also tried this code:
wtf = 15
for i in range(10):
    DMD.set_background(intensity = wtf, both_buffers = False)
    DMD.swap_buffer()
    DMD.expose_pattern(exposed_frames = -1)
    time.sleep(1)
    DMD.stop_exposure()
    time.sleep(1)
    DMD.swap_buffer()

It should do the same thing each time, but instead each iteration seems to set a slice of the background to 15:

https://github.com/user-attachments/assets/bbd94e8a-0b0c-454a-8bb9-6a63e59a6d17

**Comment by davidsachs** [comment]
All fixed now. I had set spidev.bufsize instead of spidev.bufsiz.

Thanks for building all of this!

**Comment by NemoAndrea** [comment]
Alright, nice that you found the source of the problem, and always good to hear that someone is able to replicate everything with the instructions! If you found anything unclear, or you had to do something that was not described in the docs, I would love to hear about it!

If you end up getting your project working, I'd also love to get a link or email to it!
